{application,fubbit,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{fubbit_app,[]}},
              {env,[]},
              {modules,[fubbit,fubbit_app,fubbit_connection,fubbit_records,
                        fubbit_sup]}]}.
